# -*- coding: utf-8 -*-
"""pemvis pt4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_5akxIf4mVIALmTyzswSCNAkg1odkcz
"""

print("\833c")
#import libraries

import numpy as np
import matplotlib.pyplot as plt


#tentukan wilayah domain diagram cartesian dan rasio lebar dan tinggi diagram

x = np.linspace(-8,8,10000)
plt.figure(figsize=(8,6.5))

#tentukan persamaan matematika yang diinginkan

y = x -x -0
y1 = (4-x**2)**0.5
y2 = -(4-x**2)**0.5

y3 = 5 + (4-(x-5)**2)**0.5
y4 = 5 - (4-(x-5)**2)**0.5

y5 = -5 + (4-(x-5)**2)**0.5
y6 = -5 - (4-(x-5)**2)**0.5

y7 = 5 + (4-(x+5)**2)**0.5
y8 = 5 - (4-(x+5)**2)**0.5

y9 = -5 + (4-(x+5)**2)**0.5
y10 = -5 - (4-(x+5)**2)**0.5

plt.plot(x, y, '-k')
plt.plot(x, y1, '-r', label ='y1, y2')
plt.plot(x, y2, '-r')
plt.plot(x, y3, '-g', label ='y3, y4')
plt.plot(x, y4, '-g')
plt.plot(x, y5, '-b', label ='y5, y6')
plt.plot(x, y6, '-b')
plt.plot(x, y7, '-y', label ='y7, y8')
plt.plot(x, y8, '-y')
plt.plot(x, y9, '-y', label ='y9, y10')
plt.plot(x, y10, '-y')

plt.legend(loc='upper center')
plt.grid()
plt.show()

"""latihan buat micky mouse"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.transforms as transforms

# Fungsi untuk menggambar kepala Mickey Mouse
def draw_mickey_head(ax, angle=0):
    x = np.linspace(-12, 12, 10000)

    # Persamaan untuk kepala Mickey Mouse
    y1 = np.sqrt(25 - (x - 5)**2) + 5
    y2 = -np.sqrt(25 - (x - 5)**2) + 5
    y3 = np.sqrt(4 - x**2)

    # Plot kepala Mickey Mouse
    ax.plot(x, y1, '-k')
    ax.plot(x, y2, '-k')
    ax.plot(x, y3, '-k')

    # Mengatur transformasi untuk memutar gambar
    trans = transforms.Affine2D().rotate_deg(angle)
    for line in ax.lines:
        line.set_transform(line.get_transform() + trans)

# Fungsi untuk mengubah sudut putaran gambar
def update_rotation(value):
    ax.clear()
    draw_mickey_head(ax, value)
    ax.set_xlim(-12, 12)
    ax.set_ylim(-5, 10)
    ax.set_aspect('equal', adjustable='box')
    ax.axis('off')
    ax.set_title(f'Mickey Mouse Head Rotation: {value} degrees')
    plt.draw()

# Membuat gambar awal dengan sudut 0
fig, ax = plt.subplots(figsize=(8, 5.5))
draw_mickey_head(ax)

# Menambahkan slider untuk mengubah sudut putaran
plt.subplots_adjust(bottom=0.2)
axangle = plt.axes([0.25, 0.1, 0.65, 0.03])
rotation_slider = plt.Slider(axangle, 'Rotation', 0, 360, valinit=0, valstep=1)
rotation_slider.on_changed(update_rotation)

plt.show()

"""kurva"""

print("\833c")
#import libraries

import numpy as np
import matplotlib.pyplot as plt

#tentukan wilayah domain diagram cartesian dan rasio lebar dan tinggi diagram

x = np.linspace(-4,4,10000)
plt.figure(figsize=(3,30))

#gambar lingkaran kecil titik pada 0,0
plt.plot(x,  (0.01-x**2)**0.5,    '-k')
plt.plot(x,  -((0.01-x**2)**0.5), '-k')

#tentukan persamaan matematika yang diinginkan
y = x - x - 0
y1 = x**3 - 2*x**2 - 5*x + 6
plt.plot(x, y, '-k')
plt.plot(x, y1, '-r', label='y1')

plt.legend(loc='upper left')
plt.grid()
plt.show()

"""latihan kurva"""

print("\833c")
#import libraries

import numpy as np
import matplotlib.pyplot as plt

#tentukan wilayah domain diagram cartesian dan rasio lebar dan tinggi diagram

x = np.linspace(-4,4,10000)
plt.figure(figsize=(3,30))

#gambar lingkaran kecil titik pada 0,0
plt.plot(x,  (0.01-x**2)**0.5,    '-k')
plt.plot(x,  -((0.01-x**2)**0.5), '-k')

#tentukan persamaan matematika yang diinginkan
x1,y1 = (-1,0)
x2,y2 = (1,0)
x3,y3 = (2,0)

y=(x+1)(x-1)(x-2)
y=(x**3-2*x**2-x+2)

plt.legend(loc='upper left')
plt.grid()
plt.show()